import { ArrowUpRight, CheckCircle2, Clock3, Mail, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";

const contactInfo=[
 {Icon:MapPin,title:"Visit",value:< >Sandip University<br/>Sijoul, Madhubani<br/>Bihar - 847235</>},
 {Icon:Phone,title:"Call",value:<><a href="tel:+916200576221">+91 6200576221</a><br/><a href="tel:+917320893482">+91 7320893482</a></>},
 {Icon:Mail,title:"Email",value:<><a href="mailto:nishant805180@gmail.com">nishant805180@gmail.com</a><br/><a href="mailto:nishant620057@gmail.com">nishant620057@gmail.com</a></>}
];
export default function Contact(){
 return <main className="contact-premium">
  <section className="contact-hero-new"><div className="contact-hero-copy-new"><span className="contact-eyebrow">SMART CITY SUPPORT</span><h1>Let’s build a city<br/><em>that listens.</em></h1><p>Need help with the portal, want to share feedback, or simply want to connect? We’re here to keep civic communication clear and human.</p><div className="contact-actions"><a className="contact-btn-primary" href="mailto:nishant620057@gmail.com">Email the founder <ArrowUpRight size={17}/></a><a className="contact-btn-ghost" href="/track">Track a complaint</a></div><div className="contact-trust"><span><CheckCircle2 size={15}/> Citizen focused</span><span><CheckCircle2 size={15}/> Transparent</span><span><CheckCircle2 size={15}/> Accessible</span></div></div><div className="contact-signal"><div className="contact-signal-icon"><MessageCircle size={25}/></div><span>THE IDEA</span><strong>Technology should feel human.</strong><p>A simpler way for citizens and civic teams to stay connected.</p><div className="contact-signal-line"/></div></section>
  <section className="contact-section-new"><div className="contact-heading"><span>GET IN TOUCH</span><h2>Choose the channel<br/>that works for you.</h2></div><div className="contact-info-grid">{contactInfo.map(({Icon,title,value})=><article className="contact-info-new" key={title}><div className="contact-icon-new"><Icon size={21}/></div><span>{title}</span><div>{value}</div></article>)}</div></section>
  <section className="contact-founder"><div className="founder-photo-new"><img src="/pic.jpeg" alt="Nishant Singh Vats, Founder"/><span><i/> Founder</span></div><div className="founder-copy-new"><span className="contact-eyebrow">MEET THE FOUNDER</span><h2>Nishant Singh Vats</h2><b>Founder · Smart City Portal</b><p>The Smart City Portal is built around one simple goal: make civic communication more accessible, organized and transparent for citizens and the teams working to resolve their issues.</p><div className="founder-points"><span><strong>01</strong>Citizen-first experience</span><span><strong>02</strong>Complaint transparency</span><span><strong>03</strong>Modern civic technology</span></div><a href="mailto:nishant620057@gmail.com">Connect with Nishant <ArrowUpRight size={17}/></a></div></section>
  <section className="contact-section-new contact-support"><div className="contact-heading"><span>OUR PROMISE</span><h2>Less paperwork.<br/>More clarity.</h2></div><div className="support-grid">{[[MessageCircle,"Portal assistance","Help with registration, complaints and tracking."],[ShieldCheck,"Civic-first support","Clear information from submission to resolution."],[Clock3,"Quick response","Use the portal so every issue can be properly tracked."]].map(([Icon,t,d])=><article key={t}><div className="contact-icon-new"><Icon size={20}/></div><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 </main>
}